site_name: Brazilian System of Food Metric 
site_url: https://seusite.com.br

theme:
  name: material
  language: pt-BR
  palette:
      scheme: slate # Força o modo escuro
      primary: blue
      accent: blue
  features:
    - navigation.tabs      # ISSO CRIA O MENU NO TOPO IGUAL AO DOCKER
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - search.suggest
    - search.highlight
    - content.code.copy

# Importante: registra o arquivo CSS que criamos
extra_css:
  - stylesheets/extra.css

# Estrutura de páginas para aparecerem no topo (Abas)
nav:
  - Home: index.md
  - Start: comecar-aprender.md
  - Guia de Instalação: instalacao.md
  - Configurações: config.md
  - Referência: referencia.md